# Generated by Django 2.0.1 on 2018-01-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(max_length=255, verbose_name='内容')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Catalog')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
            },
        ),
    ]
